Вострецов Павел
urfu-2016/javascript-task-4 pull request #1
Opened 2016-10-27 16:37 UTC by fakefeik

2016-10-27 16:38 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 18

2016-10-27 16:54 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-10-27 16:54 UTC, honest-hrundel commented
@onufrienko обрати внимание решено доп. задание

2016-10-27 16:55 UTC, fakefeik commented
Пожалуй, это было намного проще

2016-10-27 16:56 UTC, onufrienko commented
Какой шустрый :) :+1: 
да, это задание проще

2016-10-28 06:57 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-10-28 06:57 UTC, honest-hrundel commented
@onufrienko обрати внимание решено доп. задание

2016-10-28 08:05 UTC, onufrienko commented on lego.js
> +        var existingFields = strings.filter(function (string) {
может, лучше fields вместо strings?

2016-10-28 08:10 UTC, fakefeik commented on lego.js
> +        var existingFields = strings.filter(function (string) {
Действительно

2016-10-28 13:56 UTC, onufrienko commented
Использовать reduce круто :)
5 отступов в двух последних методах немного пугают, но в целом, хорошо

2016-10-28 13:56 UTC, onufrienko commented
:tomato:

2016-10-28 14:12 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-10-28 14:12 UTC, honest-hrundel commented
@onufrienko обрати внимание решено доп. задание

2016-10-28 15:03 UTC, onufrienko commented
:rocket:

2016-10-28 19:48 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-10-29 12:48 UTC, VorontsovMaxim requested changes
🍅

2016-10-29 12:48 UTC, VorontsovMaxim commented on lego.js
> +        var existingFields = fields.filter(function (string) {
На мой взгляд один элемент массива `fields` лучше назвать `field`

2016-10-29 12:48 UTC, VorontsovMaxim commented on lego.js
> +            return Boolean(collection[0][string]);
При таком подходе, если у первого элемента коллекции значение поля `string` например равно 0 (в нашем случае маловероятно, разве что у Билли есть друзья, которым еще и году нет) , то мы его вообще не выберем ни в одном из элементов. Лучше сделать более общо, чтобы обрабатывались все случаи

2016-10-29 12:48 UTC, VorontsovMaxim commented on lego.js
> +    return function format(collection) {
В функции `filterIn` ты вернул анонимную функцию. Здесь тоже можно без названия, для единообразности

2016-10-29 12:48 UTC, VorontsovMaxim commented on lego.js
> +    return function select(collection) {
В функции `filterIn` ты вернул анонимную функцию. Здесь тоже можно без названия, для единообразности

2016-10-29 12:48 UTC, VorontsovMaxim commented on lego.js
> +    return function limit(collection) {
В функции `filterIn` ты вернул анонимную функцию. Здесь тоже можно без названия, для единообразности

2016-10-29 12:48 UTC, VorontsovMaxim commented on lego.js
> +            var elementCopy = getObjectWithFields(element, Object.keys(element));
Почему не `Object.assign({}, element)` ?

2016-10-29 15:35 UTC, fakefeik commented on lego.js
> +    return function select(collection) {
Именованы только те функции, для которых важен порядок их применения (например, select должен идти после всех фильтров). Те функции, которые при сортировке не нужно двигать вниз, остались безымянными. Можно, конечно, вместо функций возвращать какие-то нелепые объекты вида `{function: f, priority: p}`, но мне мой вариант показался лучше.

2016-10-29 15:38 UTC, fakefeik commented on lego.js
> +            return Boolean(collection[0][string]);
Да, тут достаточно проверки на `undefined`

2016-10-29 15:39 UTC, fakefeik commented on lego.js
> +            var elementCopy = getObjectWithFields(element, Object.keys(element));
Хотел переиспользовать функцию, теперь вижу, что по-тупому получилось

2016-10-29 15:43 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-10-29 15:43 UTC, honest-hrundel commented
@VorontsovMaxim обрати внимание решено доп. задание

2016-10-30 16:49 UTC, VorontsovMaxim commented on lego.js
> +    return function select(collection) {
Да согласен, ответ принимается)

2016-10-30 17:03 UTC, VorontsovMaxim reviewed
Вопрос на подумать (будет круто если придумаешь):
Допустим коллекция довольно большая и для нас критично время работы. Как можно ускорить твое решение?

2016-10-30 17:03 UTC, VorontsovMaxim commented on lego.js
> +        var existingFields = fields.filter(function (field) {
А так ли нужно заранее фильтровать поля? Верно ли будет в твоем случае если у первого элемента по каким то причинам нет определенного поля, а у остальных это поле есть?

2016-10-30 18:52 UTC, fakefeik commented
>Допустим коллекция довольно большая
у нас есть божественный `filterIn`, который может ее сократить, нужно только подвинуть его повыше в приоритетах

2016-10-30 18:56 UTC, fakefeik commented on lego.js
> +        var existingFields = fields.filter(function (field) {
Если не фильтровать поля, то в Object.keys(element) могут появиться элементы, которых там по сути быть не должно. Если тесты такое не проверяют, и это нормальное поведение, то можно выпилить

2016-10-30 19:02 UTC, fakefeik commented on lego.js
> +        var existingFields = fields.filter(function (field) {
С другой стороны, можно в reduce проверять на `element.hasOwnProperty`

2016-10-30 19:02 UTC, VorontsovMaxim commented
>  У нас есть божественный filterIn

👍  Именно это я имел ввиду

2016-10-30 19:04 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-10-30 19:04 UTC, honest-hrundel commented
@VorontsovMaxim обрати внимание решено доп. задание

2016-10-30 19:10 UTC, VorontsovMaxim approved these changes

2016-10-30 19:10 UTC, VorontsovMaxim commented
Принято!

2016-10-30 19:10 UTC, closed without merging