Дорохова Татьяна
urfu-2016/javascript-task-4 pull request #24
Opened 2016-11-01 11:02 UTC by DorokhovaTatiana

2016-11-01 11:03 UTC, honest-hrundel commented
:tomato: Пройдено тестов 8 из 15

2016-11-01 11:20 UTC, honest-hrundel commented
:tomato: Пройдено тестов 8 из 15

2016-11-01 11:52 UTC, honest-hrundel commented
:tomato: Пройдено тестов 8 из 15

2016-11-01 12:09 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-01 19:58 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-11-01 19:58 UTC, honest-hrundel commented
@Savichev-Igor обрати внимание решено доп. задание

2016-11-01 21:35 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 18

2016-11-01 21:39 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-11-01 21:39 UTC, honest-hrundel commented
@Savichev-Igor обрати внимание решено доп. задание

2016-11-04 09:27 UTC, Savichev-Igor commented on lego.js
> +
Самый элегантный `query`, из всех, что я видел до этого 👍

2016-11-04 09:32 UTC, Savichev-Igor commented on lego.js
> +            return order === 'asc' ? sign : -sign;
Может как-нить проще, например
![image](https://cloud.githubusercontent.com/assets/7279995/20000901/82486c2a-a29b-11e6-8162-261186b43ffd.png)

2016-11-04 09:35 UTC, Savichev-Igor commented on lego.js
> +            }, {});
Зачем-то лишнее создание объекта происходит, подумай как можно обойтись без этого и просто изменить вошедшую коллекцию

2016-11-04 09:40 UTC, Savichev-Igor commented
В остальном всё круто 🍅

2016-11-04 09:41 UTC, Savichev-Igor commented on lego.js
> +    var newCollection = JSON.parse(JSON.stringify(collection));
Ну и такое ещё обычно в try/catch оборачивают, но пусть здесь мы предполагаем, что нам всегда приходят адекватные данные

2016-11-04 10:00 UTC, Savichev-Igor commented on lego.js
> +    return FUNCTION_PRIORITY[firstFunction.name] - FUNCTION_PRIORITY[secondFunction.name];
Ну и стоит иметь ввиду, что функция сортировки должна работать по критериям -1, 0, 1. Сейчас же это будет работать, но в каких-то случаях нет =)

2016-11-04 13:46 UTC, DorokhovaTatiana commented on lego.js
> +            return order === 'asc' ? sign : -sign;
а для чего 2 > 1 : 3 < 4?

2016-11-04 13:48 UTC, DorokhovaTatiana commented on lego.js
> +    var newCollection = JSON.parse(JSON.stringify(collection));
я думала насчет try/catch, но ведь нам действительно всегда в тестах приходят корректные данные,  поэтому не стала писать

2016-11-04 13:55 UTC, DorokhovaTatiana commented on lego.js
> +    return FUNCTION_PRIORITY[firstFunction.name] - FUNCTION_PRIORITY[secondFunction.name];
Если я правильно тебя поняла, то ты говоришь про Math.sign()?

2016-11-04 15:37 UTC, Savichev-Igor commented on lego.js
> +    return FUNCTION_PRIORITY[firstFunction.name] - FUNCTION_PRIORITY[secondFunction.name];
Нет, просто интересный факт

2016-11-04 15:54 UTC, Savichev-Igor commented on lego.js
> +    filterIn: 2,
Ещё желательнее, чтобы фильтрация и прочие функции, которые уменьшают коллекцию применялись как можно раньше

2016-11-04 16:38 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-11-04 16:38 UTC, honest-hrundel commented
@Savichev-Igor обрати внимание решено доп. задание

2016-11-04 16:41 UTC, DorokhovaTatiana commented
🍏

2016-11-04 16:46 UTC, Savichev-Igor commented
В целом ок, но я думаю, что стоит поправить приоритет операций 🚀

2016-11-04 16:56 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-04 17:09 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-11-04 17:09 UTC, honest-hrundel commented
@VorontsovMaxim обрати внимание решено доп. задание

2016-11-05 11:11 UTC, VorontsovMaxim requested changes
🍅 
В целом все хорошо, нужно только исправить копирование объекта

2016-11-05 11:11 UTC, VorontsovMaxim commented on lego.js
> +    return Math.sign(FUNCTION_PRIORITY[firstFunction.name] -
Можно без `Math.sign`

2016-11-05 11:11 UTC, VorontsovMaxim commented on lego.js
> +    var newCollection = JSON.parse(JSON.stringify(collection));
При таком подходе теряются функции, даты, да и вообщем то все что не является частью json спецификации
Давайте все таки сами реализуем копирование объекта, в данном случае достаточно просто поверхностного копирования - объекты плоские

2016-11-05 11:11 UTC, VorontsovMaxim commented on lego.js
> +    .forEach(function (fun) {
Если использовать `reduce`, то можно сразу возвращать результат этой цепочки вызовов

2016-11-05 11:11 UTC, VorontsovMaxim commented on lego.js
> +            var ask = firstRecord[property] > secondRecord[property];
**asc** - ascending

2016-11-05 11:11 UTC, VorontsovMaxim commented on lego.js
> +            var desk = secondRecord[property] > firstRecord[property];
**desc** - descending

2016-11-05 11:11 UTC, VorontsovMaxim commented on lego.js
> +            return order === 'asc' ? ask : desk;
Функция использующаяся для сравнения [должна](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) возвращать числовое значение

2016-11-05 11:11 UTC, VorontsovMaxim commented on lego.js
> +
Строчка лишняя

2016-11-05 17:44 UTC, DorokhovaTatiana commented on lego.js
> +    .forEach(function (fun) {
Точно, почему я сразу об этом не подумала:)

2016-11-05 17:54 UTC, DorokhovaTatiana commented on lego.js
> +    var newCollection = JSON.parse(JSON.stringify(collection));
Да, я поняла, что не очень хорошо в данном случае использвать json.

2016-11-05 18:09 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-11-05 18:09 UTC, honest-hrundel commented
@VorontsovMaxim обрати внимание решено доп. задание

2016-11-05 18:10 UTC, DorokhovaTatiana commented
🍏

2016-11-06 12:18 UTC, VorontsovMaxim approved these changes

2016-11-06 12:18 UTC, VorontsovMaxim commented
Принято

2016-11-06 12:18 UTC, closed without merging