Ганиева Альбина
urfu-2016/javascript-task-4 pull request #30
Opened 2016-11-01 18:09 UTC by Albina-G

2016-11-01 18:09 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-01 18:48 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-01 20:25 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 18

2016-11-02 17:52 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-11-02 17:52 UTC, honest-hrundel commented
@hx0day обрати внимание решено доп. задание

2016-11-05 08:46 UTC, hx0day commented on lego.js
> +    if (kol > 1) {
Зачем вообще эта проверка?

2016-11-05 09:15 UTC, hx0day commented on lego.js
> +        masFriends = keyFunc[i](masFriends);
использования forEach, сделает твой код более читаемым

2016-11-05 09:16 UTC, hx0day commented on lego.js
> +    var priorFunc = ['format', 'limit', 'select', 'sortBy', 'or', 'and', 'filterIn'];
Можно вынести в константу

2016-11-05 09:21 UTC, hx0day commented on lego.js
> +            choiceField(field, newMasFriends[i]);
использования `reduce` и создание нового объекта, сильно упростит тебе жизнь и улучшит читаемость кода(поможет обойтись без choiceField  и compareKeys)

2016-11-05 09:26 UTC, hx0day commented on lego.js
> +        for (var i = 0; i < masFriends.length; i++) {
Это место тоже можно сделать проще использую `filter` и у нас есть indexOf

2016-11-05 09:26 UTC, hx0day commented on lego.js
> +        if (elemMasFriends[property] === values[j]) {
нас есть indexOf

2016-11-05 09:29 UTC, hx0day commented on lego.js
> +        if (order === undefined) {
почему?

2016-11-05 09:30 UTC, hx0day commented on lego.js
> +        if (order === undefined) {
отсутствие order, означает что у нас происходит какой-то вид сортировки по умолчанию

2016-11-05 09:32 UTC, hx0day commented on lego.js
> +            findKeyForFormat(newMasFriends[i], property, formatter);
зачем выносит в отдельную переменную,  можно использовать `map` или `forEach`

2016-11-05 09:33 UTC, hx0day commented on lego.js
> +            var newMasOut = newMasFriends.filter(function (element) {
можно же сказать просто `return newMasFriends.filter(...)` или `return masFriends.slice().filter(...)`

2016-11-05 09:34 UTC, hx0day commented on lego.js
> +            for (var i = 0; i < arg.length; i++) {
`forEach` будет уместней

2016-11-05 09:35 UTC, hx0day commented
🍅

2016-11-06 12:27 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-06 12:28 UTC, hx0day commented on lego.js
> +        console.info(item);
Зачем `console.info`

2016-11-06 12:28 UTC, hx0day commented on lego.js
> +    var indexEl1 = PRIOPITY_FUNC.indexOf(el1.name);
кажется что это можно переписать теперь как 
`return  PRIOPITY_FUNC.indexOf(el1.name)<PRIOPITY_FUNC.indexOf(el2.name)`

2016-11-06 12:29 UTC, Albina-G commented on lego.js
> +        console.info(item);
Ой, это я для себя писала, забыла убрать

2016-11-06 12:29 UTC, hx0day commented on lego.js
> +            for (var index = 0; index < masKey.length; index++) {
может `forEach` конструкция currentValeu[masKey[index]] выглядит громостко и трудно читаемо

2016-11-06 12:30 UTC, hx0day commented on lego.js
> +        console.info('sortBy');
зачем?

2016-11-06 12:30 UTC, hx0day commented on lego.js
> +        console.info(newMasFriends);
зачем?

2016-11-06 12:31 UTC, Albina-G commented on lego.js
> +        console.info(newMasFriends);
Прошу прощения, тоже для себя писала и забыла убрать

2016-11-06 12:46 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-06 12:51 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-11-06 12:51 UTC, honest-hrundel commented
@hx0day обрати внимание решено доп. задание

2016-11-06 19:58 UTC, hx0day commented
🚀

2016-11-07 05:49 UTC, dzlk requested changes
Все, что отмечено ❗️ обязательно, остальное на усмотрение

2016-11-07 05:49 UTC, dzlk commented on lego.js
> +        return Object.assign({}, elementMas);
❗️ Задания должны быть выполнены в ES5.1, а `Object.assign` – часть ES6. Поэтому нужно сделать без него

2016-11-07 05:49 UTC, dzlk commented on lego.js
> +    return masFriends;
❗️ Во-первых, так как call возвращает массив, sort возвращает массив, то их можно объединить в цепочку:

```
[].slice.call(arguments, 1)
    .sort()
    .forEach()
```

Во-вторых, тут больше подходит reduce, так как по факту ты хочешь применить каждый элемент массива последовательно над какой-то коллекцией. Получится что-то такое:

```
return [].slice.call(arguments, 1)
    .sort()
    .reduce(..., masFriends)
```

2016-11-07 05:49 UTC, dzlk commented on lego.js
> +    var masFriends = collection.map(function (elementMas) {
❗️ Название masFriends слишком конкретное. Я же могу воспользоваться библиотекой не для коллекции друзей?
Ну и если уж называть так, то friends, а элемент коллекции просто item

2016-11-07 05:49 UTC, dzlk commented on lego.js
> +    return PRIOPITY_FUNC.indexOf(el1.name) < PRIOPITY_FUNC.indexOf(el2.name);
❗️ Намного оптимальнее приоритеты функций хранить в виде объекта. Так как, доставания значения по ключу намного быстрее, чем пробежка по массиву.

2016-11-07 05:49 UTC, dzlk commented on lego.js
> +        var newMasFriends = masFriends.slice();
❗️ Зачем slice?

2016-11-07 05:49 UTC, dzlk commented on lego.js
> +                    delete currentValeu[item];
Value не правильно написано. Не очень понятно что за суффикс mas в контексте этой функции

2016-11-07 05:49 UTC, dzlk commented on lego.js
> +    var field = [].slice.call(arguments);
❗️ там несколько полей

2016-11-07 05:49 UTC, dzlk commented on lego.js
> +        }, 0);
❗️ Очень странный reduce. Почему ноль аккумелятор, а посел возвращается пустая строка?
Для чего нужен previousValue?
Предлагаю переписать. Так как тебе нужно операцию селект выполнить на каждым элементом коллекции и вернуть новый, а размерность входного и выходного массивов одинаковая, значит нужно использовать map. Так как у нас есть набор полей которые надо превратить в объект, то тут подойдет reduce по полям (fields) и копированием полей из текущего элемента
Примерно так
```
return collection.map(function (item) {
  retutn fields.reduce(function (newItem, field) {  ... }, {});
})
```

2016-11-07 05:49 UTC, dzlk commented on lego.js
> +        var newMasFriends = masFriends.filter(function (item) {
Лишняя переменная

2016-11-07 05:49 UTC, dzlk commented on lego.js
> +        newMasFriends.reverse();
❗️ Очень не оптимально переворачивать массив. Просто измени знак сортировки. Там где возвращаала -1 нужно вернуть 1 и наоборот

2016-11-07 05:49 UTC, dzlk commented on lego.js
> +        var newMasFriends = masFriends.slice();
❗️ Лишний слайс и переменная. Больше подходит map

2016-11-07 05:49 UTC, dzlk commented on lego.js
> +        var newMasFriends = masFriends.slice(0, Math.min(masFriends.length, count));
❗️ Лишняя перменная. Можно не делать Math.min

2016-11-07 05:49 UTC, dzlk commented on lego.js
> +        var args = [].slice.call(arguments);
❗️ Не информативные названия переменной.

2016-11-07 05:49 UTC, dzlk commented on lego.js
> +                    return arg(newMasFriends).indexOf(element) >= 0;
❗️ Реализовано не оптимально. Ты три раза по массиву пробежишь. Первый раз на фильтре, второй в функции, третий в indexOf. Давай улучшать

2016-11-07 05:49 UTC, dzlk commented on lego.js
> +            var newMasFriends = masFriends.slice();
❗️ Зачем slice?

2016-11-07 05:49 UTC, dzlk commented on lego.js
> +                newMasFriends = item(newMasFriends);
❗️ НЕ инфомартивные названия arg и item. К слову по arg вообще не понятно, что это массив

2016-11-07 05:49 UTC, dzlk commented on lego.js
> +            return newMasFriends;
❗️ Почему реализация and так сильно отличается от or? Почему не заменить some и every?
Аналогично по оптимальности, можно проще

2016-11-07 05:49 UTC, dzlk commented
🍅

2016-11-08 19:57 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-08 20:05 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-08 20:09 UTC, honest-hrundel commented
:tomato: Пройдено тестов 16 из 18

2016-11-08 20:30 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 18

2016-11-09 03:09 UTC, dzlk commented
Альбина, отпиши сюда зеленым яблоком, когда можно будет смотреть

2016-11-09 10:24 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 18

2016-11-09 11:05 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 15

2016-11-09 14:49 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 18

2016-11-09 14:56 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 18

2016-11-09 14:58 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 18

2016-11-09 15:01 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 18

2016-11-09 15:04 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 18

2016-11-09 15:08 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-11-09 15:08 UTC, honest-hrundel commented
@dzlk обрати внимание решено доп. задание

2016-11-09 15:13 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 18

2016-11-09 15:15 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-09 15:39 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-11-09 15:39 UTC, honest-hrundel commented
@dzlk обрати внимание решено доп. задание

2016-11-09 15:57 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-11-09 15:57 UTC, honest-hrundel commented
@dzlk обрати внимание решено доп. задание

2016-11-09 15:59 UTC, Albina-G commented
🍏

2016-11-09 16:05 UTC, Albina-G commented
@dzlk 🍏

2016-11-09 16:17 UTC, dzlk requested changes
Стало лучше. Отметил теперь только критичные вещи, к остальным придираться уже не стал

2016-11-09 16:17 UTC, dzlk commented on lego.js
> +    return obj;
Тут лучше подходит reduce

2016-11-09 16:17 UTC, dzlk commented on lego.js
> +            var keysItem = Object.keys(item);
Лишняя переменная

2016-11-09 16:17 UTC, dzlk commented on lego.js
> +        var sortByKey = function (a, b) {
Лишняя переменная

2016-11-09 16:17 UTC, dzlk commented on lego.js
> +            item[property] = formatter(item[property]);
❗️ А если проперти не существовал на объекте? Мы его создадим?

2016-11-09 16:17 UTC, dzlk commented on lego.js
> +        var masFunctions = [].slice.call(arguments, 0);
❗️ Я все еще не понимаю смысл префикса mas. Это создает шум в коде, причем ничего не девая в замен

2016-11-09 16:17 UTC, dzlk commented on lego.js
> +            }, masElements);
Почему тут не сделано по аналогии с `or`?

2016-11-09 16:17 UTC, dzlk commented on lego.js
> +function sortFunc(el1, el2) {
не информативные названия

2016-11-09 16:18 UTC, dzlk commented
🍅

2016-11-09 17:35 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-09 17:37 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-11-09 17:37 UTC, honest-hrundel commented
@dzlk обрати внимание решено доп. задание

2016-11-09 17:54 UTC, Albina-G commented
@dzlk 🍏

2016-11-10 15:04 UTC, closed without merging

2016-11-10 15:04 UTC, dzlk commented on lego.js
> +            });
Тут надо было написать все тоже самое, что и в or, только заменить some на every