Николаев Вадим
urfu-2016/javascript-task-4 pull request #33
Opened 2016-11-01 18:46 UTC by v0kuzyo

2016-11-01 18:46 UTC, honest-hrundel commented
:tomato: Пройдено тестов 0 из 15

2016-11-01 18:53 UTC, honest-hrundel commented
:tomato: Пройдено тестов 0 из 15

2016-11-01 19:01 UTC, honest-hrundel commented
:tomato: Пройдено тестов 0 из 15

2016-11-02 16:36 UTC, honest-hrundel commented
:tomato: Пройдено тестов 3 из 15

2016-11-02 16:43 UTC, honest-hrundel commented
:tomato: Пройдено тестов 4 из 15

2016-11-02 17:05 UTC, honest-hrundel commented
:tomato: Пройдено тестов 5 из 15

2016-11-02 17:11 UTC, honest-hrundel commented
:tomato: Пройдено тестов 5 из 15

2016-11-02 17:15 UTC, honest-hrundel commented
:tomato: Пройдено тестов 5 из 15

2016-11-02 17:31 UTC, honest-hrundel commented
:tomato: Пройдено тестов 5 из 15

2016-11-02 17:52 UTC, honest-hrundel commented
:tomato: Пройдено тестов 1 из 15

2016-11-02 18:06 UTC, honest-hrundel commented
:tomato: Пройдено тестов 4 из 15

2016-11-02 18:33 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-04 12:03 UTC, Dotokoto commented on lego.js
>  exports.query = function (collection) {
Эта функция вышла слишком большой. Надо порефакторить и вынести разные логические части в отдельные функции

2016-11-04 12:06 UTC, Dotokoto commented on lego.js
> +        return collection.map(function (friend) {
Здесь лучше использовать forEach. Тогда не будет последней строки ```return friend;```. И ты ведь не создаешь новый массив, а только меняешь поле у каждого элемента старого массива.

2016-11-04 12:09 UTC, dotokoto commented on lego.js
> +        return collection.reverse();
reverse  - дополнительная операция над массивом. Можно от нее избавиться. Используй order прямо в функции сортировки, и в зависимости от него сортируй

2016-11-04 12:10 UTC, dotokoto commented on lego.js
> +        collection.forEach(function (friend) {
Новая коллекция здесь не нужна. И посмотри метод массива filter

2016-11-04 12:11 UTC, Dotokoto commented on lego.js
> +    var prioritet = ['select', 'filterIn', 'sortBy', 'format', 'limit'];
priority

2016-11-04 12:13 UTC, Dotokoto commented on lego.js
> +var SELECT = [];
Для чего используется этот массив?

2016-11-04 12:13 UTC, Dotokoto commented
:tomato: Посмотрела первый раз. Есть вопросы, и пока не очень понятно, как работает функция query. Порефактори ее, и посмотрю еще раз

2016-11-04 13:14 UTC, v0kuzyo commented on lego.js
> +var SELECT = [];
Содержит поля, которые используются для вывода. В общем, это данные, собранные вызовами функции exports.select

2016-11-09 08:59 UTC, Dotokoto commented
:rocket:

2016-11-09 18:56 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-16 10:39 UTC, steppefox requested changes
🍅

2016-11-16 10:39 UTC, steppefox commented on lego.js
> +    var friends = collection.map(function (friend) {
Вот это лучше вынести в отдельную функцию. Так же, можно чуть чуть сократить используя `reduce`:

```
return Object.keys(friend).reduce(function (acc, key) {
  acc[key] = friend[key];
  return acc;
}, {});
```

2016-11-16 10:39 UTC, steppefox commented on lego.js
> +        if (priority.indexOf(f1.name) > priority.indexOf(f2.name)) {
Вот смотри, для того что-бы сравнить пару функций, твоему алгоритму придется пробежаться по массиву (`indexOf` это линейный поиск) минимум два раза за одну итерацию `sort`, а то и 4 раза. А итераций в `sort` тоже достаточно. В итоге что-бы отсортировать функции по приоритету, создается куча проходов цикла. Подумай, может намного удобнее заранее сложить приоритеты функций каким-нибудь объектом (диктом)?

2016-11-16 10:39 UTC, steppefox commented on lego.js
> +            if (values.indexOf(friend[property]) !== -1) {
Можно просто сократить до `return values.indexOf(friend[property]) !== -1`

2016-11-16 10:39 UTC, steppefox commented on lego.js
>      console.info(property, order);
А это точно должно было остаться? oO

2016-11-16 10:39 UTC, steppefox commented on lego.js
> +var SELECT = [];
Обычно заглавными буквами называются константные переменные

2016-11-16 10:39 UTC, steppefox commented on lego.js
>      console.info(count);
Зачем здесь `console`? oO

2016-11-16 10:39 UTC, steppefox commented on lego.js
>      console.info(property, formatter);
`console` =(

2016-11-16 10:39 UTC, steppefox commented on lego.js
> +    friends = friends.map(function (friend) {
Вот эта часть кода на самом деле должна быть в функции `select`, и тогда не будет необходимости в глобальной переменной `SELECT`

2016-11-16 10:39 UTC, steppefox commented on lego.js
> +            SELECT.forEach(function (sel) {
Такую блок кода можно было заменить и на простой `indexOf`

2017-10-11 11:09 UTC, closed without merging