Иван Матасов
urfu-2016/javascript-task-4 pull request #35
Opened 2016-11-01 20:23 UTC by IvanMatasov

2016-11-01 20:24 UTC, honest-hrundel commented
:tomato: Пройдено тестов 10 из 15

2016-11-01 21:53 UTC, honest-hrundel commented
:tomato: Пройдено тестов 10 из 15

2016-11-02 09:21 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-04 12:14 UTC, Dotokoto commented on lego.js
> +    if (func.length === 0) {
if (!func.length) - то же самое, а запись короче

2016-11-04 12:18 UTC, Dotokoto commented on lego.js
> +    for (var i = 0; i < func.length; i++) {
Попробуй вместо простого цикла использовать ```func.reduce()```

2016-11-04 12:22 UTC, Dotokoto commented on lego.js
> +            }).reduce(function (prev, value) {
Что-то сложное здесь происходит, и map, и filter, и reduce. Для начала предлагаю не вызывать по цепочке map и reduce, а вынести результат map в переменную. Может, тогда станет немного понятней

2016-11-04 12:23 UTC, Dotokoto commented on lego.js
> +
Если в функции только одна строка с return, то перед ней не надо оставлять пустую строку

2016-11-04 12:24 UTC, Dotokoto commented on lego.js
> +            var compare = a[property] > b[property] ? 1 : -1;
А что насчет случая, когда ```a[propery] === b[property]``` ?

2016-11-04 12:25 UTC, Dotokoto commented on lego.js
> +        var duplicateCollection = Object.assign(collection);
Для чего здесь копировать коллекцию? По условиям задания, ты можешь выполнять format на старой

2016-11-04 12:25 UTC, Dotokoto commented on lego.js
> +
лишняя пустая строка

2016-11-04 12:25 UTC, Dotokoto commented on lego.js
> +
еще одна лишняя пустая строка

2016-11-04 12:26 UTC, Dotokoto commented
:tomato: Посмотрела, есть некоторые замечания. Жду исправлений

2016-11-04 16:58 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-07 08:54 UTC, Dotokoto commented on lego.js
> +    format: 2
limit лучше делать перед format. Тогда в format нужно будет обрабатывать меньше объектов

2016-11-07 08:56 UTC, Dotokoto commented on lego.js
> +    var duplicateCollection = JSON.parse(JSON.stringify(collection));
Хитро, но если бы у тебя были поля типа Date, то не сработало бы :) Но по условиям этой задачи - ок

2016-11-07 08:57 UTC, Dotokoto commented on lego.js
> +    func.reduce(function (prev, value) {
``` return func.reduce(...) ``` и последняя строка ```return duplicateCollection;``` будет не нужна

2016-11-07 08:58 UTC, Dotokoto commented on lego.js
> +            record = objectValue;
1) Зачем это присваивание? 
2) Почему objectValue? Это же просто объект (или элемент коллекции)

2016-11-07 08:59 UTC, Dotokoto commented
:rocket:

2016-11-07 09:47 UTC, hrundik requested changes
🍅

2016-11-07 09:47 UTC, hrundik commented on lego.js
> +    var duplicateCollection = JSON.parse(JSON.stringify(collection));
Хитро, но нечестно. Давайте делать без хаков.

2016-11-07 09:47 UTC, hrundik commented on lego.js
> +            record = objectValue;
Присваивание действительно не нужно

2016-11-07 15:16 UTC, hrundik requested changes
🍅

2016-11-07 15:16 UTC, hrundik commented on lego.js
> +        return Object.assign({}, objectValue);
`Object.assign` нельзя, это `ES2015`. Мы остаёмся пока в рамках `ES5`

2016-11-07 15:41 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-16 15:48 UTC, IvanMatasov commented
:green_apple:

2016-11-16 16:20 UTC, hrundik commented on lego.js
> +        return Object.assign({}, objectValue);
Я ещё раз повторю, что в этом задании `Object.assign` нельзя использовать.

2016-11-16 16:20 UTC, hrundik commented
🍅

2016-11-16 20:06 UTC, IvanMatasov commented on lego.js
> +        return Object.assign({}, objectValue);
извиняюсь, не тот файл запушил)

2016-11-16 20:10 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 15

2016-11-16 20:26 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-17 18:13 UTC, IvanMatasov commented
:green_apple:

2016-11-21 07:51 UTC, hrundik commented
Годится

2016-11-21 07:51 UTC, closed without merging