Кужелев Евгений
urfu-2016/javascript-task-4 pull request #40
Opened 2016-11-02 10:16 UTC by askeip

2016-11-02 10:16 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-03 13:41 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-03 13:43 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 15

2016-11-03 13:53 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-04 19:18 UTC, FrodoTheTrue commented on lego.js
> +    var coll = [].slice.call(collection);
args и coll плохие названия

2016-11-04 19:18 UTC, FrodoTheTrue commented on lego.js
> +var funcPriorities = {
нужно оформить как константу

2016-11-04 19:21 UTC, FrodoTheTrue commented on lego.js
> +    return convertForQuery(filterFriends, [property, values]);
Интересный способ, но достаточно здесь посто вернуть функцию, которая уже умела бы работать с аргументами, а не тащить аргументы в другие функции. И назвать возвращаемую функцию так же как и как и экспортируемую, чтобы работать с одинаковыми именами (например, расставлять приоритет для имен которые есть у нас, а не у каких-то абстрактных selectFields или filterFriends). Это не сложно исправить, код сильно упростится и станет чище. Не надо будет делать convertForQuery

2016-11-04 19:22 UTC, FrodoTheTrue commented on lego.js
> +    for (var filter in this[1]) {
Вот яркий пример, почему твой способ неудобен - аргументы исходной функции недоступны и пришлось использовать хаки

2016-11-04 19:22 UTC, FrodoTheTrue commented on lego.js
> +    var copy = obj.constructor();
зачем тут это?

2016-11-04 19:23 UTC, FrodoTheTrue commented
:tomato:

2016-11-04 19:25 UTC, FrodoTheTrue commented on lego.js
> +    for (var filter in this[1]) {
Название функции интересное

2016-11-04 20:50 UTC, honest-hrundel commented
:tomato: Пройдено тестов 10 из 15

2016-11-04 20:50 UTC, askeip commented on lego.js
> +    var copy = obj.constructor();
в map я изменяю свойства объекта, а в задании сказано, что изначальный объект не должен быть изменен

2016-11-05 09:10 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-05 09:24 UTC, askeip commented
🍏  (не совсем понял, нужно слать или нет, ну ладно)

2016-11-05 14:50 UTC, FrodoTheTrue commented on lego.js
> +    var copy = obj.constructor();
я имею ввиду зачем пустой объект создается через constructor() ?

2016-11-05 14:53 UTC, askeip commented on lego.js
> +    var copy = obj.constructor();
просто скопировал первый ответ по запросу javascript clone, думаю тут можно и без этого обойтись

2016-11-05 14:54 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-05 16:07 UTC, FrodoTheTrue commented on lego.js
> +    var queries = [].slice.call(arguments).slice(1);
можно здесь просто [].slice.call(arguments, 1)

2016-11-05 16:07 UTC, FrodoTheTrue commented on lego.js
> +    for (var query in queries) {
так конечно работает, но усложняет код, используй forEach или reduce

2016-11-05 16:08 UTC, FrodoTheTrue commented on lego.js
> +var FUNC_PRIORITIES = {
будет эффективнее если сделать фильтрацию раньше

2016-11-05 16:08 UTC, FrodoTheTrue commented
Стало намного лучше, поправь еще мелочи и будет ок

2016-11-05 16:08 UTC, FrodoTheTrue commented
:tomato:

2016-11-05 16:18 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-05 16:22 UTC, FrodoTheTrue commented
:rocket:

2016-11-11 11:48 UTC, Vittly requested changes
есть мелкие замечания - нужно поправить
🍅

2016-11-11 11:48 UTC, Vittly commented on index.js
> +    lego.sortBy('age', 'asc'), // Бывает только asc (от меньшего к большему) или desc (наоборот)
зачем переставил?

2016-11-11 11:48 UTC, Vittly commented on lego.js
> +    var friends = [].slice.call(collection);
`collection` - нормальный массив, у него прямо можно звать `slice`

2016-11-11 11:48 UTC, Vittly commented on lego.js
> +    return 0;
на самом деле можно возвращать: отрицательное число, нуль, положительное число. Поэтому обычно такие функции реализуют как: `return b - a;`. Переделай пожалуйста

2016-11-11 11:48 UTC, Vittly commented on lego.js
> +    }, friends);
лучше вместо `acc` писать что-то более осознанное - тут, например, `prevResult`

2016-11-11 11:48 UTC, Vittly commented on lego.js
> +    return 0;
а почему этот кусок про приоритеты и функцию-компаратор утащил сюда? Пусть будет наверху

2016-11-11 11:48 UTC, Vittly commented on lego.js
> +                        .hasOwnProperty(params[param])) {
не понял конструкции - распиши пожалуйста, что ты тут делаешь

2016-11-11 11:48 UTC, Vittly commented on lego.js
> +            for (var filter in values) {
прошу переделать на `return values.some(...);`

2016-11-11 11:48 UTC, Vittly commented on lego.js
> +                        .hasOwnProperty(params[param])) {
почему для прохода по массиву используется `for( in )` ?

2016-11-11 11:48 UTC, Vittly commented on lego.js
> +        if (obj.hasOwnProperty(attr)) {
Почему не использовать `Object.keys`?

2016-11-11 11:48 UTC, Vittly commented on lego.js
> +        if (obj.hasOwnProperty(attr)) {
и `reduce`

2016-11-11 11:49 UTC, Vittly commented
я не увидел отбивки про тебя, поэтому задача подвисла - прошу в следующий раз писать мне в slack если такое случается

2016-11-11 18:46 UTC, askeip commented on index.js
> +    lego.sortBy('age', 'asc'), // Бывает только asc (от меньшего к большему) или desc (наоборот)
тестил работает ли сортировка по приоритетам

2016-11-11 18:52 UTC, askeip commented on lego.js
> +                        .hasOwnProperty(params[param])) {
на курсе weba на матмехе преподаватель часто использует for in, скоро привыкну к forEach. В целом просто проверяю, если такого свойства у друга нет, то и у нового объекта не должно появиться

2016-11-11 19:12 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-11 19:14 UTC, askeip commented
🍏

2016-11-12 06:40 UTC, Vittly requested changes
еще немного замечаний прошу поправить
🍅

2016-11-12 06:40 UTC, Vittly commented on lego.js
> +            return mappedFriend;
можно были и правильнее было через `reduce`

2016-11-12 06:40 UTC, Vittly commented on lego.js
> +            }
нет, зачем ты возвращаешь `friend`-а? Фильтр как работает? Если колбек возвращает `true` на элемент - элемент проходит фильтрацию, иначе - не проходит. Стало быть, нужно было писать:

```js
return friends.filter(function (friend) {
    return values.some(function (filterValue) { // кмк, такое название понятнее - а что что такое x === filter?
        return friend[property] === filterValue;
    });
});
```

угу?

2016-11-12 06:40 UTC, Vittly commented on lego.js
> +            } else if (friend1[property] > friend2[property]) {
можно без `else`-а

2016-11-12 06:40 UTC, Vittly commented on lego.js
> +function clone(obj) {
хелпер бы наверз унести к сортировщику функций - пусть будут все вместе

2016-11-12 06:40 UTC, Vittly commented on index.js
> +    lego.sortBy('age', 'asc'), // Бывает только asc (от меньшего к большему) или desc (наоборот)
окей

2016-11-12 06:56 UTC, askeip commented on lego.js
> +            }
согласен, сглупил

2016-11-12 07:08 UTC, honest-hrundel commented
:tomato: Пройдено тестов 10 из 15

2016-11-12 07:12 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 15

2016-11-12 07:19 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-12 07:20 UTC, askeip commented
🍏

2016-11-12 08:07 UTC, Vittly commented on lego.js
> +            return friend1[property] > friend2[property] ? comparer : 0;
👍

2016-11-12 08:07 UTC, Vittly approved these changes

2016-11-12 08:08 UTC, Vittly commented
круто, молодец!

2016-11-12 08:08 UTC, closed without merging