Козлова Валерия
urfu-2016/javascript-task-4 pull request #49
Opened 2016-11-02 15:59 UTC by OnaHochetNaMars

2016-11-02 16:00 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-02 16:17 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-02 16:19 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 15

2016-11-02 16:34 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 15

2016-11-02 16:56 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 15

2016-11-02 18:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-02 18:37 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-02 18:43 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-04 20:59 UTC, chipolinka commented on lego.js
> +        if ({}.hasOwnProperty.call(collection, key)) {
Уверена, что это можно переписать попроще

2016-11-04 21:00 UTC, chipolinka commented on lego.js
> +            if (!(Object.keys(res[i]).length === 0)) {
Сложная конструкция, упрости

2016-11-04 21:01 UTC, chipolinka commented on lego.js
> +                if ({}.hasOwnProperty.call(friend, key)) {
Большая вложенность

2016-11-04 21:01 UTC, chipolinka commented on lego.js
> +    var n = values.length;
Название

2016-11-04 21:02 UTC, chipolinka commented on lego.js
> +                if (obj[property] === values[i]) {
Попробуй использовать встроенный `filter`

2016-11-04 21:03 UTC, chipolinka commented on lego.js
> +    if (order === 'asc') {
А не лучше ли проверку делать в самой функции `sortBy`? И без переменной `newOrder`

2016-11-04 21:04 UTC, chipolinka commented on lego.js
> +            if ({}.hasOwnProperty.call(friend, property)) {
Аналогично

2016-11-04 21:05 UTC, chipolinka commented
Привет! Есть косяки, тянущиеся еще с прошлого задания. Старайся от них со временем избавляться :)

2016-11-04 21:05 UTC, chipolinka commented
:tomato:

2016-11-08 15:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-08 15:43 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-08 15:55 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-08 16:07 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-08 16:33 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-08 16:35 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-08 16:37 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-08 16:38 UTC, OnaHochetNaMars commented
:green_apple:

2016-11-08 18:27 UTC, chipolinka commented on lego.js
> +            var res = {};
Не стоит сокращать названия переменных

2016-11-08 18:28 UTC, chipolinka commented on lego.js
> +        var filterCollection = collection.filter(function (friend) {
Может лучше сразу вернуть новую коллекцию, не запихивая её в переменную?

2016-11-08 18:29 UTC, chipolinka commented on lego.js
> +        collection.splice(count);
Почему именно `splice`?

2016-11-08 18:31 UTC, chipolinka commented
:rocket:

2016-11-08 18:36 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-10 18:27 UTC, OnaHochetNaMars commented
:green_apple:

2016-11-11 11:24 UTC, Vittly requested changes
есть замечания 🍅

2016-11-11 11:24 UTC, Vittly commented on lego.js
> +    'limit'
лимит можно делать до формата - будет быстрее - нам точно не надо форматировать то, что не прошло через лимит

2016-11-11 11:24 UTC, Vittly commented on lego.js
> +function cloneFriend(collection) {
а точно аргумент коллекция?

2016-11-11 11:24 UTC, Vittly commented on lego.js
> +    keys.forEach(function (key) {
можно:
* не делать переменную `keys` - использовать по месту результат
* не делать переменную `friend` и использовать `reduce`

2016-11-11 11:24 UTC, Vittly commented on lego.js
> +    }
это надо переписать через `map`:

```js

var friends = collection.map(function(friend) {
    return cloneFriend(friend); // profit!
});
```

2016-11-11 11:24 UTC, Vittly commented on lego.js
> +    });
```js

return functions.reduce(function(prevResult, func) {
    return func(prevResult);
}, friends);
```

2016-11-11 11:24 UTC, Vittly commented on lego.js
> +            return result;
через `reduce` давай

2016-11-11 11:24 UTC, Vittly commented on lego.js
> +            return false;
давай используем `some` внутри?

```js

return values.some(function(value) {
    return friend[property] === value;
});
```

2016-11-11 11:24 UTC, Vittly commented on lego.js
> +            return order === 'desc';
прикольная идея! можно записать тернарником:

```js

return friend1[property] > friend2[property] ? order === 'asc' : order === 'desc';
```

2016-11-11 11:24 UTC, Vittly commented on lego.js
> +        return collection;
лучше `map`  использовать

2016-11-11 11:24 UTC, Vittly commented on lego.js
> +        collection.splice(count);
+1

ага, почему? Этот же нужен, чтобы добавлять элементы, удалять элементы. Есть более подходящий для наших целей `slice`.

2016-11-12 11:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-12 11:44 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 15

2016-11-12 11:50 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-12 11:51 UTC, OnaHochetNaMars commented
:green_apple:

2016-11-12 17:54 UTC, Vittly requested changes
еще надо чуток подправить
🍅

2016-11-12 17:54 UTC, Vittly commented on lego.js
> +
лишняя пустая строка

2016-11-12 17:54 UTC, Vittly commented on lego.js
> +    return Object.keys(friend).reduce (function (result, key) {
лишний пробел после `reduce`?

2016-11-12 17:54 UTC, Vittly commented on lego.js
> +    });
ага, а можно короче:
```js
var friends = collection.map(cloneFriend);
```

круто же?)

2016-11-12 17:54 UTC, Vittly commented on lego.js
> +    if (functions.length === 0) {
~~этот `if` лучше делать в начале, чтоб не заниматься лишний раз копированием `collection` - если это не надо делать~~

лучше убрать этот `if` - просто сортировка дальше не отработает (так как массив пустой) и `reduce` вернет исходное значение - то есть коллекцию

2016-11-12 17:54 UTC, Vittly commented on lego.js
> +
лишняя пустая строка

2016-11-12 17:54 UTC, Vittly commented on lego.js
> +
не нужны все эти пустые строки)

2016-11-12 17:54 UTC, Vittly commented on lego.js
> +                if (friend[key]) {
лучше спрашивать через `hasOwnPropeprty`

2016-11-12 17:54 UTC, Vittly commented on lego.js
> +
эти пустые строки долой)

2016-11-12 17:54 UTC, Vittly commented on lego.js
> +            friend[property] = formatter (friend[property]);
в данном случае ты меняешь сами элементы коллекции - `map` вернет еще одну копию коллекции - зачем? Лучше сделай `forEach`, измени элементы коллекции и верни ее

2016-11-12 19:56 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-13 09:13 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-13 09:15 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-13 09:18 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-13 09:20 UTC, OnaHochetNaMars commented
исправила

2016-11-13 09:21 UTC, OnaHochetNaMars commented
:green_apple:

2016-11-13 10:52 UTC, Vittly commented on lego.js
> +            friend[property] = formatter (friend[property]);
поидее не хватает `if`-а, проверяющего, что свойство есть в объекте. Мало ли человек допустил ошибку, `select`-ом убрал форматируемое поле?

2016-11-13 10:52 UTC, Vittly commented on lego.js
> +            friend[property] = formatter (friend[property]);
такое же может быть? Поправь и будешь совсем молодец)

2016-11-13 10:53 UTC, Vittly commented on lego.js
> +            friend[property] = formatter (friend[property]);
🍅

2016-11-13 17:40 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-13 17:41 UTC, OnaHochetNaMars commented
:green_apple:

2016-11-14 05:23 UTC, Vittly approved these changes

2016-11-14 05:23 UTC, Vittly commented
всё круто, молодец!

2016-11-14 05:23 UTC, closed without merging