Голубев Дмитрий
urfu-2016/javascript-task-4 pull request #55
Opened 2016-11-02 17:02 UTC by zokeer

2016-11-02 17:02 UTC, Sergey-Ubogov commented
тащи димас

2016-11-02 17:02 UTC, zokeer commented
Следишь за мной?)

2016-11-02 17:03 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-02 18:02 UTC, melanholy commented
все следят за твоими успехами

2016-11-03 06:29 UTC, onufrienko commented
Привет! :) Я посмотрю твой пр сегодня вечером либо завтра, не теряй меня, если что.

2016-11-03 08:13 UTC, zokeer commented
Да как тебе удобно будет

2016-11-04 07:33 UTC, onufrienko commented on lego.js
> +    'filterIn': 5,
В данном случае нет никакой необходимости оборачивать поля в кавычки

2016-11-04 07:34 UTC, onufrienko commented on lego.js
> +        return Priors[another.name] - Priors[one.name];
👍

2016-11-04 07:34 UTC, onufrienko commented on lego.js
> +    for (var i = 1; i < arguments.length; i++) {
Можно для чуточку более приятного восприятия добавить пустую строку перед блоком for.
А ещё можно использовать при желании forEach :)

2016-11-04 07:35 UTC, onufrienko commented on lego.js
> +        funcList.push(arguments[i]);
А можно и map попробовать

2016-11-04 07:36 UTC, onufrienko commented on lego.js
> +    var selectedFields = Array.from(arguments);
ES6? :)

2016-11-04 07:37 UTC, onufrienko commented on lego.js
> +            var properties = Object.keys(elem);
Ты используешь переменную properties единожды, может, в ней нет смысла?
Или ты это сделал для более удобного восприятия?

2016-11-04 07:58 UTC, onufrienko commented on lego.js
> +        return collection;
Можно же и  return collection.forEach(function (elem)) ...

2016-11-04 08:00 UTC, onufrienko commented on lego.js
> +        return collection;
Можно попробовать сразу возвращать collection.filter()

2016-11-04 08:01 UTC, onufrienko commented on lego.js
> +                return one[property] > another[property] ? 1 : -1;
Чтобы избавиться от collection.reverse() ниже, можно просто здесь умножать на 1 или -1 в зависимости от порядка

2016-11-04 08:01 UTC, onufrienko commented
🍅

2016-11-05 09:50 UTC, zokeer commented on lego.js
> +    'filterIn': 5,
Я понимаю, что в JS так, но вообще, если обернуть, то будет нагляднее.

2016-11-05 09:55 UTC, zokeer commented on lego.js
> +            var properties = Object.keys(elem);
Именно, цепочка вызовов keys и проход по ним показались мне достаточно непонятными для чтения.

2016-11-05 09:57 UTC, zokeer commented on lego.js
> +                return one[property] > another[property] ? 1 : -1;
Хорошо, но мне кажется, что это какая-то не очевидная константа. У меня медленно, но зато наглядно) Но я переделаю)

2016-11-05 16:33 UTC, onufrienko commented on lego.js
> +            var properties = Object.keys(elem);
Хорошо, давай оставим так

2016-11-05 16:33 UTC, onufrienko commented on lego.js
> +    'filterIn': 5,
Не знаю, как насчет наглядности, но не надо так :)

2016-11-05 17:27 UTC, zokeer commented on lego.js
> +    var selectedFields = Array.from(arguments);
Миру не угоден `Array.from`?))

2016-11-05 17:33 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-05 17:35 UTC, onufrienko commented on lego.js
> +    var funcList = Array.from(arguments).slice(1);
плюшки ES6, конечно, крутые, но правильно ли я помню, что вам пока не дали добро ими пользоваться в домашках? :)

2016-11-05 18:25 UTC, zokeer commented on lego.js
> +    var funcList = Array.from(arguments).slice(1);
нельзя использовать библиотеки, решающие большую часть задания, про ES6 ничего не говорили, да и эта штука не такая уж и кардинальная, легко записать одним циклом, а так выглядит приличнее. Думаешь, надо поменять на forEach?

2016-11-05 18:27 UTC, onufrienko commented on lego.js
> +    var funcList = Array.from(arguments).slice(1);
таки нашла :)
![image](https://cloud.githubusercontent.com/assets/14929766/20032604/aa90c91c-a39e-11e6-888e-0f28c6a80328.png)

2016-11-05 18:33 UTC, onufrienko commented on lego.js
> +    var funcList = Array.from(arguments).slice(1);
я соглашусь, что так выглядит гораздо лучше. И ништяки es6 сама ценю и люблю, но давай пока обойдемся старым добрым циклом или же чего-либо в духе
var args = Array.prototype.slice.call(arguments, 1);

2016-11-05 18:41 UTC, zokeer commented on lego.js
> +    var funcList = Array.from(arguments).slice(1);
Хорошо, сейчас перезалью, спасибо за поиск)

2016-11-05 18:48 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-05 18:58 UTC, onufrienko commented
:rocket:

2016-11-06 09:19 UTC, dzlk requested changes
Все что помечено ❗️ обязательно, остально на усмотрение

2016-11-06 09:19 UTC, dzlk commented on lego.js
> +var Priors = {
❗️ С большой буквы обычно называют функции-конструкторы. Тут это просто объект и должен быть назван с маленькой

2016-11-06 09:19 UTC, dzlk commented on lego.js
> +    limit: 2
почему функции не разместить в порядке убывания их значения? Сейчас страдает читаемость

2016-11-06 09:19 UTC, dzlk commented on lego.js
> +    var friends = JSON.parse(JSON.stringify(collection));
❗️ Так клонировать объекты нельзя. JSON сильно ограниченнее формат, чем javascript, поэтому ты можешь потерять какие-нибудь свойства. Самый простой пример:
```
> JSON.parse(JSON.stringify({ a: undefined }))
{}
```

2016-11-06 09:19 UTC, dzlk commented on lego.js
> +    return friends;
❗️Функция `sort` возвращает массив, поэтому методы можно объединить в цепочку. Фукнция `forEach` здесь подходит хуже чем `reduce`, так как по сути тебе нужно выполнить каждое действие, аккумулируя результат
Хочу увидеть примерно следующее
```
returns funcList
    .sort(...)
    .reduce(...)
```

2016-11-06 09:19 UTC, dzlk commented on lego.js
> +        });
❗️ Свойств для выбора будет прилетать скорее всего меньше, чем полей в объекте. Поэтому лучше итерироваться по ним и заодно проверять существовать свойства на объекте. Это позволит убрать вызов `Object.keys` и сделать код чуточку читаемее

2016-11-06 09:19 UTC, dzlk commented on lego.js
> +            if (elem.hasOwnProperty(property)) {
❗️ Зачем эта проверка?

2016-11-06 09:19 UTC, dzlk commented on lego.js
> +            if (one.hasOwnProperty(property) && another.hasOwnProperty(property)) {
❗️ Зачем эта проверка? Объекты одинаковой структуры – это гарантируется

2016-11-06 09:19 UTC, dzlk commented on lego.js
> +    var sign = { 'asc': 1, 'desc': -1 };
Сложно, проще было тернарником сделать:
`sign = order === 'asc' ? 1 : -1`

2016-11-06 09:19 UTC, dzlk commented on lego.js
> +            if (elem.hasOwnProperty(property)) {
👍 Молодец, что добавил проверку

2016-11-06 09:19 UTC, dzlk commented on lego.js
> +        collection.forEach(function (elem) {
❗️ лучше `map`. Так как по факту ты хочешь над кажды элементом сделать операцию и вернуть новый элемент (в твоем случае тотже)

2016-11-06 09:19 UTC, dzlk commented
🍅

2016-11-06 09:21 UTC, dzlk commented
Жду смайлика зеленого яблочка, когда можно будет смотреть вновь

2016-11-06 13:17 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-07 02:55 UTC, dzlk requested changes
🍅

2016-11-07 02:55 UTC, dzlk commented on lego.js
> +        friends.push(Object.assign({}, elem));
❗️ Задания мы просим выполнять в рамках спецификации ES5.1. `Object.assign` – это часть ES6. Давай без него

2016-11-07 02:55 UTC, dzlk commented on lego.js
> +    }, friends);
я обычно делаю так
```js
return funcList
    .sort(function (one, another) {
        return priors[another.name] - priors[one.name];
    })
    .reduce(function (prevArr, func) {
        return func(prevArr);
    }, friends);
```

2016-11-07 02:55 UTC, dzlk commented on lego.js
> +    }).reduce(function (prevArr, func) {
❗️ не понятно почему эта переменная называется prevArr. В reduce ушла friends, а в функцию пришло collection.
При том, что prevArr слишком абстрактная, а friends слишком конкретная. Я же могу воспользоваться твоей библиотекой не для друзей?

2016-11-07 02:55 UTC, dzlk commented on lego.js
> +        return collection.slice().map(function (elem) {
❗️ Зачем slice?

2016-11-07 02:55 UTC, dzlk commented on lego.js
> +            selectedFields.forEach(function (field) {
Это больше reduce. Аккумуляция свойств в объект.

2016-11-07 02:55 UTC, dzlk commented on lego.js
>          return collection;
❗️ Функция map возвращает массив. Поэтому можно сразу результат возвращать
```
return collection.map()
```

2016-11-07 14:44 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-07 14:44 UTC, zokeer commented
🍏

2016-11-08 04:16 UTC, dzlk approved these changes

2016-11-08 04:16 UTC, dzlk commented on lego.js
> +    for (var attr in elem) {
❗️ Итерироваться по ключам объекта проще через Object.keys (вам об этом рассказывали).
Тут лучше сделать `return Object.keys().reduce(..., {});`

2016-11-08 04:16 UTC, dzlk commented on lego.js
> +    return copiedCollection;
❗️ Ну map же

2016-11-08 04:16 UTC, closed without merging