Тимохина Вера
urfu-2016/javascript-task-4 pull request #56
Opened 2016-11-02 17:21 UTC by VeraTimox

2016-11-02 17:21 UTC, honest-hrundel commented
:tomato: Пройдено тестов 7 из 15

2016-11-02 17:36 UTC, Sergey-Ubogov commented
таще вера

2016-11-02 17:48 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-03 13:50 UTC, mironov-alexey commented on lego.js
> +
Линтер правда здесь просит отступы? А то не в первый раз уже вижу у разных людей :(

2016-11-03 13:53 UTC, mironov-alexey commented on lego.js
> +function sortArrayFunctions(arrayFunctions) {
лучше отделять функции пустой строкой

2016-11-03 13:56 UTC, m1ralx requested changes

2016-11-03 13:56 UTC, mironov-alexey commented on lego.js
> +                return 1 * Number(sign);
а зачем вызов Number?

2016-11-03 13:56 UTC, mironov-alexey commented on lego.js
> +        return collection.slice(0, count);
Что будет, если count < 0?

2016-11-03 13:56 UTC, mironov-alexey commented
:tomato:

2016-11-03 17:19 UTC, VeraTimox commented on lego.js
> +
Просит, к сожалению(

2016-11-03 17:20 UTC, VeraTimox commented on lego.js
> +                return 1 * Number(sign);
Линтер просит Number=(

2016-11-03 17:31 UTC, VeraTimox commented on lego.js
> +        return collection.slice(0, count);
В тестах такого нет, я не знаю, надо ли проверять по условию задачи. То есть, если count<0, вернутся элементы с 0 по length-count. Не знаю, это неверно по логике задачи? Что, если надо вернуть всех, кроме count последних друзей.

2016-11-03 17:36 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-03 17:37 UTC, veratim1996 commented on lego.js
> +function sortArrayFunctions(arrayFunctions) {
Исправила

2016-11-06 06:48 UTC, mironov-alexey commented on lego.js
> +        return collection.slice(0, count);
Если не сказано, то я бы сделал так, как здравый смысл подсказывает -- выбросил бы информативное исключение.

2016-11-06 06:50 UTC, mironov-alexey commented on lego.js
> +
В любом случае его можно обмануть, если хочешь и возвращать разность приоритетов функций, а ещё лучше -- знак этой разности. Будет короче и не менее понятно

2016-11-06 06:51 UTC, mironov-alexey commented
🚀

2016-11-06 10:43 UTC, VeraTimox commented on lego.js
> +        return collection.slice(0, count);
А тут уже надо знать, чего от меня ждет Хрюндель) Если я выкину информативное исключение, а он его не ждет, я тесты не пройду. Понятно, что так лучше делать в самостоятельном проекте, но тут мы по сути дописываем чужой проект, так что надо на это ориентироваться.

2016-11-07 10:26 UTC, ulitcos commented on lego.js
> +            for (var key in friend) {
Вместо цикла лучше использовать Object.keys

2016-11-07 10:26 UTC, ulitcos commented on lego.js
> +                if (selectArgs.indexOf(key) === -1) {
Вариант хороший, но еще обрати внимание, что есть вот такой [вариант](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes)

2016-11-07 10:26 UTC, ulitcos commented on lego.js
> +
посмотри вот [этот](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) метод. С ним не нужно будет создавать arrayFriends

2016-11-07 10:26 UTC, ulitcos commented on lego.js
> +    };
Зачем такие сложности с sign? 
Можно сильно проще:
```
return function sortBy (collection){
                return collection.sort(function(a, b){
                    if(order === 'desc') {
                        return a[property] < b[property];
                    } else {
                        return a[property] > b[property];
                    }
                })
            };
```

2016-11-07 10:26 UTC, ulitcos commented on lego.js
> +    });
Давай упростим функцию до такого вида:
```
arrayFunctions.sort(function (a, b) {
                return orderFunctions[a.name] > orderFunctions[b.name]
            });
```

2016-11-07 10:26 UTC, ulitcos commented
🍅

2016-11-08 18:07 UTC, VeraTimox commented on lego.js
> +                if (selectArgs.indexOf(key) === -1) {
Да, я знаю этот вариант, но нам вроде нельзя пользоваться этой спецификацией. Только пятой

2016-11-08 18:53 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-08 18:54 UTC, VeraTimox commented
🍏

2016-11-10 09:54 UTC, ulitcos commented
Принял

2016-11-10 09:54 UTC, closed without merging