Назарова Галина
urfu-2016/javascript-task-4 pull request #59
Opened 2016-11-02 18:12 UTC by galkadaw

2016-11-02 18:12 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 15

2016-11-02 18:31 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-02 18:33 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 15

2016-11-02 18:50 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 15

2016-11-02 19:08 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-05 16:42 UTC, FrodoTheTrue commented on lego.js
> +var PRIORITY_OF_METHODS = {
фильтрацию лучше делать первой

2016-11-05 16:42 UTC, FrodoTheTrue commented on lego.js
> +    var commands = params.slice(1);
можно сразу commands = [].slice.call(arguments, 1)

2016-11-05 16:42 UTC, FrodoTheTrue commented on lego.js
> +    var args = [].slice.call(arguments);
лучше fields

2016-11-05 16:43 UTC, FrodoTheTrue commented on lego.js
> +        collection.forEach(function (index) {
index здесь совсем плохое нахвание

2016-11-05 16:43 UTC, FrodoTheTrue commented on lego.js
> +            }
-1 в противном случае тоже надо вернуть

2016-11-05 16:43 UTC, FrodoTheTrue commented on lego.js
> +        return collection.map(function (index) {
нужно поменять название, здесь нет отношения к индексам

2016-11-05 16:43 UTC, FrodoTheTrue commented on lego.js
> +                var indexClone = Object.assign({}, index);
Object.assign использовать нельзя, скопируй по другому

2016-11-05 16:44 UTC, FrodoTheTrue commented
:tomato:

2016-11-06 13:07 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-07 14:42 UTC, FrodoTheTrue commented
🚀

2016-11-08 04:08 UTC, dzlk requested changes
ВСе что помечено ❗️ требует внимание, остальное на усмотрение

2016-11-08 04:08 UTC, dzlk commented on lego.js
> +    'limit': 3
❗️ Лучше отсортировать методы по их значениям и не использовать одинаковые. Например, я бы выполнял select и format после limit

2016-11-08 04:08 UTC, dzlk commented on lego.js
> +    }
Зачем эта проверка?

2016-11-08 04:08 UTC, dzlk commented on lego.js
> +    var commands = [].slice.call(arguments, 1);
❗️ Если это commands то почему константа называется PRIORITY_OF_METHODS ?

2016-11-08 04:08 UTC, dzlk commented on lego.js
> +        .forEach(function (query) {
❗️ Тут чуть больше подходит reduce. Мы прогоняем некоторое начальное значение через все элементы массива.

2016-11-08 04:08 UTC, dzlk commented on lego.js
> +    var copyCollection = collection.slice();
❗️ Это не скопирует элементы. Нужно пройтись по ним и сделать копию, тогда больше об этом не придется думать в коде

2016-11-08 04:08 UTC, dzlk commented on lego.js
> +        if (PRIORITY_OF_METHODS[second.name] > PRIORITY_OF_METHODS[first.name]) {
❗️ ЛУчше сохранить в переменную, так уменьшится зароможденность в коде

2016-11-08 04:08 UTC, dzlk commented on lego.js
> +        .forEach(function (query) {
Чтобы не было такого смещения в цепочке вызовов я делаю так:

```
return commands
    .sort()
    .reduce()
```

2016-11-08 04:08 UTC, dzlk commented on lego.js
> +        return collectionNewFriends;
❗️ Тут лучше подходит map. Так как размерность входного и выходного массивов совпадают, а мы просто обрабатываем каждый элемент и возвращаем новый

2016-11-08 04:08 UTC, dzlk commented on lego.js
> +            for (var key in item) {
❗️ Итерацию лучше делать Object.keys(item).reduce()

2016-11-08 04:08 UTC, dzlk commented on lego.js
> +            }
❗️ Сложновато получилось. Давай для каждого элемента бегать по филдам, а не по полям элемента. Тогда можно будет заменить for..in  и if на одну итерацию по fields
```
return fields.reduce();
```

2016-11-08 04:08 UTC, dzlk commented on lego.js
> +            newCollection.reverse();
❗️ Давай избавимся от reverse. Он явно избыточен для этой задачи

2016-11-08 04:08 UTC, dzlk commented on lego.js
> +        return newCollection;
❗️ Лишняя переменная. Можно сразу вернуть результат sort

2016-11-08 04:08 UTC, dzlk commented on lego.js
> +                itemClone[property] = formatter(item[property]);
В начале написал, что как вариант можно было склонировать один раз и больше не заморачиваться об этом. Иначе приходится везде думать, портим мы объекты или нет

2016-11-08 04:08 UTC, dzlk commented on lego.js
> +        return collection.map(function (item) {
👍 Отлично

2016-11-08 04:08 UTC, dzlk commented on lego.js
> +        }
Можно этого не делать. `[1,2].slice(0, 100)` отработает правильно

2016-11-08 04:08 UTC, dzlk commented on lego.js
> +    for (var key in item) {
❗️ Object.keys + reduce

2016-11-08 04:09 UTC, dzlk commented
🍅

2016-11-09 15:26 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-09 16:22 UTC, dzlk requested changes
Осталось чуть-чуть

2016-11-09 16:22 UTC, dzlk commented on lego.js
> +    });
Это очень похоже на map

2016-11-09 16:22 UTC, dzlk commented on lego.js
> +                if (item.hasOwnProperty(field) && fields.indexOf(field) !== -1) {
Проще было идти таки по fields. Ушла бы проверка indexOf

2016-11-09 16:22 UTC, dzlk commented on lego.js
> +        if (item.hasOwnProperty(field)) {
❗️ Object.keys возвращает только собственные свойства. Эта проверка бессмысленная

2016-11-09 16:22 UTC, dzlk commented
🍅

2016-11-09 16:25 UTC, galkadaw commented on lego.js
> +    });
а не reduce?

2016-11-09 16:31 UTC, dzlk commented on lego.js
> +    });
Размерность входного и выходного массива одинаковые, новый массив состоит из измененных элементах входного. Поэтому больше map)

2016-11-09 16:32 UTC, galkadaw commented on lego.js
> +    });
спасибо)

2016-11-09 16:32 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-09 16:33 UTC, dzlk commented
👍

2016-11-09 16:33 UTC, closed without merging