Барбанягра Владислав
urfu-2016/javascript-task-4 pull request #62
Opened 2016-11-02 19:04 UTC by Vladyabra

2016-11-02 19:05 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-02 19:17 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-02 19:23 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-02 20:13 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-02 20:21 UTC, honest-hrundel commented
:tomato: Пройдено тестов 5 из 15

2016-11-02 20:29 UTC, honest-hrundel commented
:tomato: Пройдено тестов 5 из 15

2016-11-02 20:55 UTC, honest-hrundel commented
:tomato: Пройдено тестов 5 из 15

2016-11-02 21:00 UTC, honest-hrundel commented
:tomato: Пройдено тестов 5 из 15

2016-11-02 21:03 UTC, honest-hrundel commented
:tomato: Пройдено тестов 6 из 15

2016-11-02 21:10 UTC, honest-hrundel commented
:tomato: Пройдено тестов 5 из 15

2016-11-02 21:18 UTC, honest-hrundel commented
:tomato: Пройдено тестов 5 из 15

2016-11-02 22:24 UTC, honest-hrundel commented
:tomato: Пройдено тестов 8 из 15

2016-11-02 22:33 UTC, honest-hrundel commented
:tomato: Пройдено тестов 8 из 15

2016-11-02 22:49 UTC, honest-hrundel commented
:tomato: Пройдено тестов 8 из 15

2016-11-02 22:52 UTC, honest-hrundel commented
:tomato: Пройдено тестов 10 из 15

2016-11-02 22:54 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2016-11-02 23:30 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-11-02 23:30 UTC, honest-hrundel commented
@Lakate обрати внимание решено доп. задание

2016-11-04 10:01 UTC, Lakate reviewed
привет!
ты молодец, но надо поправить замечания

2016-11-04 10:01 UTC, Lakate commented on lego.js
> +var orderOfCommands = ['sortBy', 'filterIn', 'or', 'and', 'selector', 'format', 'limit'];
лучше фильтрацию проводить самой первой, а не сортировку. Так у тебя сразу останетс меньше возможных друзей

2016-11-04 10:01 UTC, Lakate commented on lego.js
> +var orderOfCommands = ['sortBy', 'filterIn', 'or', 'and', 'selector', 'format', 'limit'];
а еще лучше поменять местами `format`и `limit` по тем же причинам

2016-11-04 10:01 UTC, Lakate commented on lego.js
> +var orderOfCommands = ['sortBy', 'filterIn', 'or', 'and', 'selector', 'format', 'limit'];
и мы по-другому обозначаем костантные значения. Будет хорошо, если еще разок прочитаешь гайд

2016-11-04 10:01 UTC, Lakate commented on lego.js
> +    var commands = [].slice.call(arguments).slice(1)
`var commands = [].slice.call(arguments, 1)`

2016-11-04 10:01 UTC, Lakate commented on lego.js
> +    for (var i = 0; i < commands.length; i++) {
попробуй с помощью `reduce` переписать этот цикл?

2016-11-04 10:01 UTC, Lakate commented on lego.js
> +        return collection.map(function (e) {
`e` - плохое название. Старайся давать осмысленные названия переменным

2016-11-04 10:01 UTC, Lakate commented on lego.js
> +        return collection.filter(function (e) {
аналогично

2016-11-04 10:01 UTC, Lakate commented on lego.js
> +            for (var i = 0; i < properties.length; i++) {
попроьуй с помощью `map` переписать?

2016-11-04 10:01 UTC, Lakate commented on lego.js
> +        return collection.map(function (e) {
тоже поменять название

2016-11-04 10:01 UTC, Lakate commented on lego.js
> +                for (var i = 0; i < filters.length; i++) {
попробуй использовать метод `some`?

2016-11-04 10:01 UTC, Lakate commented
🍅

2016-11-10 12:48 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-11-10 12:48 UTC, honest-hrundel commented
@Lakate обрати внимание решено доп. задание

2016-11-10 13:08 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-11-10 13:08 UTC, honest-hrundel commented
@Lakate обрати внимание решено доп. задание

2016-11-10 13:11 UTC, Vladyabra commented
Привет, @Lakate

Вроде всё исправил

2016-11-10 13:13 UTC, Vladyabra commented on lego.js
> +                return null;
Но вот этот момент мне не очень нравится, может, можно элегантней?

2016-11-12 12:39 UTC, Lakate commented on lego.js
> +    });
По правилам курса, мы пока ограничиваем решение спецификацией ES5.1 – Object.assign придётся реализовать.

2016-11-12 12:39 UTC, Lakate commented on lego.js
> +    var result = collection.map(function (entry) {
это еще не результат, а просто скопированная исходная коллекция

2016-11-12 12:39 UTC, Lakate commented on lego.js
> +    result = commands.reduce(function (prev, next) {
лучше дополнить названия аргументов, а то непонятно что в них кроется

2016-11-12 12:40 UTC, Lakate commented on lego.js
> +                return null;
тут можно тоже воспользоваться reduce и будет элегантно))

2016-11-12 12:40 UTC, Lakate commented
🍅

2016-11-12 12:40 UTC, Lakate commented
и лучше в слак стучись, тут долго не вижу

2016-11-16 18:28 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-11-16 18:29 UTC, honest-hrundel commented
@Lakate обрати внимание решено доп. задание

2016-11-18 16:00 UTC, Lakate reviewed
молодец!

2016-11-18 16:00 UTC, Lakate commented on lego.js
> +        }
не критично, но можно попроще сделать)

2016-11-18 16:00 UTC, Lakate commented
дальше с ментором

2016-11-18 16:00 UTC, Lakate commented
🚀

2016-11-21 15:49 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-11-21 15:49 UTC, honest-hrundel commented
@steppefox обрати внимание решено доп. задание

2016-12-07 07:34 UTC, steppefox requested changes
🍅

2016-12-07 07:34 UTC, steppefox commented on lego.js
> +        return ORDER_OF_COMMANDS.indexOf(a.name) - ORDER_OF_COMMANDS.indexOf(b.name);
Чем плох `indexOf`? Тем что это линейный поиск, и что-бы найти какой-то элемент нужно каждый раз бегать по массиву, а это плохо. Да массив небольшой,  но все же, лучше переделать структуру `ORDER_OF_COMMANDS` в объект (дикт/словарь), что-бы порядок функции можно было получить за O(1)

2016-12-07 07:34 UTC, steppefox commented on lego.js
> - * @param {Array} collection
Зачем ты усиленно стираешь JSDoc? Верни все назад >__< JSDoc замечательная весчь

2016-12-07 07:34 UTC, steppefox commented on lego.js
> +exports.select = function select() {
Зачем здесь именованная функция?

2016-12-07 07:34 UTC, steppefox commented on lego.js
> +    return function selector(collection) {
`selector` переименовать в `select`, что-бы не было разницы в именах с `exports.select`

2016-12-07 07:34 UTC, steppefox commented on lego.js
> +    var collectionCopy = collection.map(function (entry) {
Этот код по принципу работы похож на тот же который используется в `select`. Возможно код можно вынести в отдельную функцию и использовать и там и там?
типа: `function copyCollection(fields) { }`

2016-12-07 14:50 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-12-07 14:50 UTC, honest-hrundel commented
@steppefox обрати внимание решено доп. задание

2016-12-07 15:07 UTC, steppefox requested changes
🍅

2016-12-07 15:07 UTC, steppefox commented on lego.js
> +.reduce(function (collection, name, i) {
Не ленись, сделай руками объект ;D

2016-12-07 15:20 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2016-12-07 15:20 UTC, honest-hrundel commented
@steppefox обрати внимание решено доп. задание

2016-12-07 15:20 UTC, Vladyabra commented
🍏

2016-12-07 15:56 UTC, steppefox approved these changes

2016-12-07 15:56 UTC, closed without merging